version: "3.5"
services:
  spark-worker-1:
    image: bde2020/spark-worker:3.1.1-hadoop3.2
    container_name: spark-worker-1
    restart: always
    ports:
      - "8081:8081"
    environment:
      - "SPARK_MASTER=spark://10.123.252.192:27077"

  spark-worker-2:
    image: bde2020/spark-worker:3.1.1-hadoop3.2
    container_name: spark-worker-2
    restart: always
    ports:
      - "8082:8082"
    environment:
      - "SPARK_MASTER=spark://10.123.252.192:27077"
