version: "3.5"
services:
  # spark-master:
  #   image: bde2020/spark-master:3.1.1-hadoop3.2
  #   container_name: spark-master
  #   ports:
  #     - "8080:8080"
  #     - "7077:7077"
  #   environment:
  #     - INIT_DAEMON_STEP=setup_spark
  #   networks:
  #     cscourse:
  #       ipv4_address: 172.202.0.9
  spark-worker-1:
    image: bde2020/spark-worker:3.1.1-hadoop3.2
    container_name: spark-worker-1
    ports:
      - "8081:8081"
    environment:
      - "SPARK_MASTER=spark://10.123.252.192:27077"
    # networks:
    #   cscourse:
    #     ipv4_address: 172.202.0.10
  spark-worker-2:
    image: bde2020/spark-worker:3.1.1-hadoop3.2
    container_name: spark-worker-2
    ports:
      - "8082:8082"
    environment:
      - "SPARK_MASTER=spark://10.123.252.192:27077"
    # networks:
    #   cscourse:
    #     ipv4_address: 172.202.0.11
        
networks:
  cscourse:
    name: hadoop
    ipam:
      config:
        - subnet: 172.202.0.0/24